version : "3.8"

services:
  eureka_server:
    build: ./eurikaServer/.
    container_name: eurekaServer
    ports:
      - "8761:8761"
    networks:
      - spring-net
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  notification-app:
    build: ./notification/.
    container_name: notificationApp
    ports:
      - "7070:7070"
    depends_on:
      - mysql-db
      - eureka_server
    networks:
      - spring-net
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE : product
    ports:
      - "27017:27017"
    networks:
      - spring-net


  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: dotinMikro
      MYSQL_ROOT_PASSWORD: FT_amir13456679
      MYSQL_PASSWORD : FT_amir13456679
    ports:
      - "3306:3306"
    networks:
      - spring-net



  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: dotinmikro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - spring-net

  product-app:
    build: ./product/.
    container_name: my-product-app
    depends_on:
      - mongo-db
      - eureka_server
    ports:
      - "8080:8080"
    environment:
     - MONGO_HOST= mongo-db
     - MONGO_PORT= 27017
     - MONGO_USER= root
     - MONGO_PASSWORD= 1234
     - MONGO_DB= product
     - SPRING_PROFILES_ACTIVE = docker
    networks:
      - spring-net



  discount-app:
      build: ./discount/.
      container_name: my-discount-app
      depends_on:
        - postgres-db
        - eureka_server
      ports:
        - "9090:9090"
      environment:
          SPRING_DATASOURCE_URL : jdbc:postgresql://postgres-db:5432/dotinmikro
          SPRING_DATASOURCE_USERNAME : postgres
          SPRING_DATASOURCE_PASSWORD: postgres
          SPRING_PROFILES_ACTIVE : docker
      networks:
        - spring-net
  gateway-app:
    image: my-gate-way
    container_name: my-gateWay-app
    depends_on:
      - eureka_server
    ports:
      - "6060:6060"
    networks:
      - spring-net


networks:
  default:
  spring-net:
    name: "spring-net"
    driver: bridge