
services:
  eureka_server:
    build: ./eurikaServer/.
    container_name: eurekaServer
    ports:
      - "8761:8761"
    networks:
      - spring-net
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  notification-app:
    build: ./notification/.
    container_name: notificationApp
    ports:
      - "7070:7070"
    depends_on:
      - mysql-db
      - eureka_server
      - axon-server
    networks:
      - spring-net
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AXON_SERVER_HOST= axon-server
      - AXON_SERVER_PORT= 8124
  axon-server:
    image: axoniq/axonserver:latest
    container_name: axon-server
    ports:
      - "8024:8024" # HTTP Dashboard
      - "8124:8124" # Command/Event/Query communication
    networks:
      - spring-net

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: dotinMikro
      MYSQL_ROOT_PASSWORD: FT_amir13456679
      MYSQL_PASSWORD : FT_amir13456679
    ports:
      - "3306:3306"
    networks:
      - spring-net



  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: dotinmikro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - spring-net

  product-app:
    build: ./product/.
    container_name: my-product-app
    depends_on:
       - mysql-db
       - axon-server
       - eureka_server
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AXON_SERVER_HOST= axon-server
      - AXON_SERVER_PORT= 8124
    networks:
      - spring-net



  discount-app:
      build: ./discount/.
      container_name: my-discount-app
      depends_on:
        - postgres-db
        - eureka_server
        - axon-server
      ports:
        - "9090:9090"
      environment:
          SPRING_DATASOURCE_URL : jdbc:postgresql://postgres-db:5432/dotinmikro
          SPRING_DATASOURCE_USERNAME : postgres
          SPRING_DATASOURCE_PASSWORD: postgres
          AXON_SERVER_HOST: axon-server
          AXON_SERVER_PORT: 8124
          SPRING_PROFILES_ACTIVE : docker
      networks:
        - spring-net
  gateway-app:
    build: ./gatewayservice/.
    container_name: my-gateWay-app
    depends_on:
      - eureka_server
    ports:
      - "6060:6060"
    networks:
      - spring-net


networks:
  default:
  spring-net:
    name: "spring-net"
    driver: bridge