server:
  port: 8080

spring:
  data:
   mongodb:
     port: 27017
     host: localhost
     database: product
     username: root
     password: 1234
     uri:  mongodb://root:1234@localhost:27017/product
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: product
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        service-name: ${spring.application.name}

#eureka:
#  client:
#    server-url:
#       defaultZone: http://localhost:8761/eureka
#  instance:
#    lease-expiration-duration-in-seconds: 20
#    lease-renewal-interval-in-seconds: 5
#    prefer-ip-address: true

