server:
  port: 8080

spring:
  data:
    mongodb:
      port: 27017
      host:
      database: product
      username: root
      password: salam
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: product

eureka:
  client:
    service-url:
      defaultZone: http://eurekaServer:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
resilience4j.circuitbreaker:
  configs:
    default:
      sliding-window-size: 10
      failure-rate-threshold: 50
      wait-duration-in-open-state: 10000
      permitted-number-of-calls-in-half-open-state: 3
resilience4j.retry:
  configs:
    default:
      max-attempts: 3
      wait-duration: 100
      enable-exponential-backoff: true
      exponential-backoff-multiplier: 3

