server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: product
  datasource:
    username: root
    password: FT_amir13456679
    url: jdbc:mysql://localhost:3306/dotinMikro
    driver-class-name: com.mysql.cj.jdbc.Driver
axon:
  axonserver:
    servers: localhost:8124
    context: default
    component-name: product-service
  serializer:
    general: jackson
eureka:
  client:
    server-url:
       defaultZone: http://localhost:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
resilience4j.circuitbreaker:
  configs:
    default:
      sliding-window-size: 10
      failure-rate-threshold: 50
      wait-duration-in-open-state: 10000
      permitted-number-of-calls-in-half-open-state: 3
resilience4j.retry:
  configs:
    default:
      max-attempts: 3
      wait-duration: 100
      enable-exponential-backoff: true
      exponential-backoff-multiplier: 3

