server:
  port: 8080

spring:
  data:
   mongodb:
     port: 27017
     host: localhost
     database: product
     username: root
     password: 1234
     uri:  mongodb://root:1234@localhost:27017/product
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: product