server:
  port: 7070
spring:
  datasource:
    username: root
    password: FT_amir13456679
    url: jdbc:mysql://mysql-db:3306/dotinMikro
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  application:
    name: notification
eureka:
  client:
    server-url:
      defaultZone: http://eureka_server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 5
    hostname: eureka_server