version : "1"

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: dotinmikro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: salam
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spring-net


  spring-app:
      image: my-discount
      container_name: my-discount-app
      depends_on:
        - postgres-db
      ports:
        - "9090:9090"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/dotinmikro
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
      networks:
        - spring-net

volumes:
  postgres-data:

networks:
  spring-net: