

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dotinMikro
    username: postgres
    password: salam
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: discount
server:
  port: 9090


eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    hostname:
