

spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/dotinmikro
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  application:
    name: DISCOUNT
server:
  port: 9090


eureka:
  client:
    service-url:
      defaultZone: http://eurekaServer:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
    prefer-ip-address: true