

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dotinmikro
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  application:
    name: discount
server:
  port: 9090


eureka:
  client:
    server-url:
      defaultZone: http://eureka-server-container:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 5
    hostname: localhost